=== benhovinga/caf-ranks/caf-ranks.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "CAF Ranks",
  "description": "A list of Canadian Armed Forces Ranks",
  "$defs":{
    "bilingual": {
      "type": "object",
      "required": ["en", "fr"],
      "additionalProperties": false,
      "properties": {
        "en": {
          "type": "string"
        },
        "fr": {
          "type": "string"
        }
      }
    }
  },
  "type": "array",
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": ["level", "element", "title", "abbreviation", "category"],
    "properties": {
      "level": {
        "type": "integer",
        "minimum": 1,
        "maximum": 19
      },
      "element": {
        "type": "array",
        "items": {
          "enum": ["CA", "RCAF", "RCN"]
        }
      },
      "title": {"$ref": "#/$defs/bilingual"},
      "abbreviation": {"$ref": "#/$defs/bilingual"},
      "category": {
        "type": "object",
        "required": ["en", "fr"],
        "properties": {
          "en": {
            "enum": [
              "General/Flag Officers",
              "Senior Officers",
              "Junior Officers",
              "Subordinate Officer",
              "Warrant Officers, Petty Officers and Senior Non-Commissioned Officers",
              "Junior Non-Commissioned Members"
            ]
          },
          "fr": {
            "enum": [
              "Officiers généraux",
              "Officiers supérieurs",
              "Officiers subalternes",
              "Officier subordonné",
              "Adjudants, officiers mariniers et sous-officiers supérieurs",
              "Militaires du rang subalternes"
            ]
          }
        }
      }
    }
  }
}

=== benhovinga/caf-ranks/caf-ranks.json
[
  {
    "level": 19,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "General",
      "fr": "Général"
    },
    "abbreviation": {
      "en": "Gen",
      "fr": "gén"
    },
    "category": {
      "en": "General/Flag Officers",
      "fr": "Officiers généraux"
    }
  },
  {
    "level": 19,
    "element": ["RCN"],
    "title": {
      "en": "Admiral",
      "fr": "Amiral"
    },
    "abbreviation": {
      "en": "Adm",
      "fr": "am"
    },
    "category": {
      "en": "General/Flag Officers",
      "fr": "Officiers généraux"
    }
  },
  {
    "level": 18,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Lieutenant-General",
      "fr": "Lieutenant-général"
    },
    "abbreviation": {
      "en": "LGen",
      "fr": "lgén"
    },
    "category": {
      "en": "General/Flag Officers",
      "fr": "Officiers généraux"
    }
  },
  {
    "level": 18,
    "element": ["RCN"],
    "title": {
      "en": "Vice-Admiral",
      "fr": "Vice-amiral"
    },
    "abbreviation": {
      "en": "VAdm",
      "fr": "vam"
    },
    "category": {
      "en": "General/Flag Officers",
      "fr": "Officiers généraux"
    }
  },
  {
    "level": 17,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Major-General",
      "fr": "Major-général"
    },
    "abbreviation": {
      "en": "MGen",
      "fr": "mgén"
    },
    "category": {
      "en": "General/Flag Officers",
      "fr": "Officiers généraux"
    }
  },
  {
    "level": 17,
    "element": ["RCN"],
    "title": {
      "en": "Rear-Admiral",
      "fr": "Contre-amiral"
    },
    "abbreviation": {
      "en": "RAdm",
      "fr": "cam"
    },
    "category": {
      "en": "General/Flag Officers",
      "fr": "Officiers généraux"
    }
  },
  {
    "level": 16,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Brigadier-General",
      "fr": "Brigadier-général"
    },
    "abbreviation": {
      "en": "BGen",
      "fr": "bgén"
    },
    "category": {
      "en": "General/Flag Officers",
      "fr": "Officiers généraux"
    }
  },
  {
    "level": 16,
    "element": ["RCN"],
    "title": {
      "en": "Commodore",
      "fr": "Commodore"
    },
    "abbreviation": {
      "en": "Cmdre",
      "fr": "cmdre"
    },
    "category": {
      "en": "General/Flag Officers",
      "fr": "Officiers généraux"
    }
  },
  {
    "level": 15,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Colonel",
      "fr": "Colonel"
    },
    "abbreviation": {
      "en": "Col",
      "fr": "col"
    },
    "category": {
      "en": "Senior Officers",
      "fr": "Officiers supérieurs"
    }
  },
  {
    "level": 15,
    "element": ["RCN"],
    "title": {
      "en": "Captain(N)",
      "fr": "Capitaine de vaisseau"
    },
    "abbreviation": {
      "en": "Capt(N)",
      "fr": "capv"
    },
    "category": {
      "en": "Senior Officers",
      "fr": "Officiers supérieurs"
    }
  },
  {
    "level": 14,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Lieutenant-Colonel",
      "fr": "Lieutenant-colonel"
    },
    "abbreviation": {
      "en": "LCol",
      "fr": "lcol"
    },
    "category": {
      "en": "Senior Officers",
      "fr": "Officiers supérieurs"
    }
  },
  {
    "level": 14,
    "element": ["RCN"],
    "title": {
      "en": "Commander",
      "fr": "Capitaine de frégate"
    },
    "abbreviation": {
      "en": "Cdr",
      "fr": "capf"
    },
    "category": {
      "en": "Senior Officers",
      "fr": "Officiers supérieurs"
    }
  },
  {
    "level": 13,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Major",
      "fr": "Major"
    },
    "abbreviation": {
      "en": "Maj",
      "fr": "maj"
    },
    "category": {
      "en": "Senior Officers",
      "fr": "Officiers supérieurs"
    }
  },
  {
    "level": 13,
    "element": ["RCN"],
    "title": {
      "en": "Lieutenant-Commander",
      "fr": "Capitaine de corvette"
    },
    "abbreviation": {
      "en": "LCdr",
      "fr": "capc"
    },
    "category": {
      "en": "Senior Officers",
      "fr": "Officiers supérieurs"
    }
  },
  {
    "level": 12,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Captain",
      "fr": "Capitaine"
    },
    "abbreviation": {
      "en": "Capt",
      "fr": "capt"
    },
    "category": {
      "en": "Junior Officers",
      "fr": "Officiers subalternes"
    }
  },
  {
    "level": 12,
    "element": ["RCN"],
    "title": {
      "en": "Lieutenant(N)",
      "fr": "Lieutenant de vaisseau"
    },
    "abbreviation": {
      "en": "Lt(N)",
      "fr": "ltv"
    },
    "category": {
      "en": "Junior Officers",
      "fr": "Officiers subalternes"
    }
  },
  {
    "level": 11,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Lieutenant",
      "fr": "Lieutenant"
    },
    "abbreviation": {
      "en": "Lt",
      "fr": "lt"
    },
    "category": {
      "en": "Junior Officers",
      "fr": "Officiers subalternes"
    }
  },
  {
    "level": 11,
    "element": ["RCN"],
    "title": {
      "en": "Sub-Lieutenant",
      "fr": "Enseigne de vaisseau de 1re classe"
    },
    "abbreviation": {
      "en": "SLt",
      "fr": "ens 1"
    },
    "category": {
      "en": "Junior Officers",
      "fr": "Officiers subalternes"
    }
  },
  {
    "level": 10,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Second Lieutenant",
      "fr": "Sous-lieutenant"
    },
    "abbreviation": {
      "en": "2Lt",
      "fr": "slt"
    },
    "category": {
      "en": "Junior Officers",
      "fr": "Officiers subalternes"
    }
  },
  {
    "level": 10,
    "element": ["RCN"],
    "title": {
      "en": "Acting Sub-Lieutenant",
      "fr": "Enseigne de vaisseau de 2e classe"
    },
    "abbreviation": {
      "en": "A/SLt",
      "fr": "ens 2"
    },
    "category": {
      "en": "Junior Officers",
      "fr": "Officiers subalternes"
    }
  },
  {
    "level": 9,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Officer Cadet",
      "fr": "Élève-officier"
    },
    "abbreviation": {
      "en": "OCdt",
      "fr": "élof"
    },
    "category": {
      "en": "Subordinate Officer",
      "fr": "Officier subordonné"
    }
  },
  {
    "level": 9,
    "element": ["RCN"],
    "title": {
      "en": "Naval Cadet",
      "fr": "Aspirant de marine"
    },
    "abbreviation": {
      "en": "NCdt",
      "fr": "aspm"
    },
    "category": {
      "en": "Subordinate Officer",
      "fr": "Officier subordonné"
    }
  },
  {
    "level": 8,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Chief Warrant Officer",
      "fr": "Adjudant-chef"
    },
    "abbreviation": {
      "en": "CWO",
      "fr": "adjuc"
    },
    "category": {
      "en": "Warrant Officers, Petty Officers and Senior Non-Commissioned Officers",
      "fr": "Adjudants, officiers mariniers et sous-officiers supérieurs"
    }
  },
  {
    "level": 8,
    "element": ["RCN"],
    "title": {
      "en": "Chief Petty Officer 1st class",
      "fr": "Premier maître de 1re classe"
    },
    "abbreviation": {
      "en": "CPO 1",
      "fr": "pm 1"
    },
    "category": {
      "en": "Warrant Officers, Petty Officers and Senior Non-Commissioned Officers",
      "fr": "Adjudants, officiers mariniers et sous-officiers supérieurs"
    }
  },
  {
    "level": 7,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Master Warrant Officer",
      "fr": "Adjudant-maître"
    },
    "abbreviation": {
      "en": "MWO",
      "fr": "adjum"
    },
    "category": {
      "en": "Warrant Officers, Petty Officers and Senior Non-Commissioned Officers",
      "fr": "Adjudants, officiers mariniers et sous-officiers supérieurs"
    }
  },
  {
    "level": 7,
    "element": ["RCN"],
    "title": {
      "en": "Chief Petty Officer 2nd class",
      "fr": "Premier maître de 2e classe"
    },
    "abbreviation": {
      "en": "CPO 2",
      "fr": "pm 2"
    },
    "category": {
      "en": "Warrant Officers, Petty Officers and Senior Non-Commissioned Officers",
      "fr": "Adjudants, officiers mariniers et sous-officiers supérieurs"
    }
  },
  {
    "level": 6,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Warrant Officer",
      "fr": "Adjudant"
    },
    "abbreviation": {
      "en": "WO",
      "fr": "adj"
    },
    "category": {
      "en": "Warrant Officers, Petty Officers and Senior Non-Commissioned Officers",
      "fr": "Adjudants, officiers mariniers et sous-officiers supérieurs"
    }
  },
  {
    "level": 6,
    "element": ["RCN"],
    "title": {
      "en": "Petty Officer 1st class",
      "fr": "Maître de 1re classe"
    },
    "abbreviation": {
      "en": "PO 1",
      "fr": "m 1"
    },
    "category": {
      "en": "Warrant Officers, Petty Officers and Senior Non-Commissioned Officers",
      "fr": "Adjudants, officiers mariniers et sous-officiers supérieurs"
    }
  },
  {
    "level": 5,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Sergeant",
      "fr": "Sergent"
    },
    "abbreviation": {
      "en": "Sgt",
      "fr": "stg"
    },
    "category": {
      "en": "Warrant Officers, Petty Officers and Senior Non-Commissioned Officers",
      "fr": "Adjudants, officiers mariniers et sous-officiers supérieurs"
    }
  },
  {
    "level": 5,
    "element": ["RCN"],
    "title": {
      "en": "Petty Officer 2nd class",
      "fr": "Maître de 2e classe"
    },
    "abbreviation": {
      "en": "PO 2",
      "fr": "m 2"
    },
    "category": {
      "en": "Warrant Officers, Petty Officers and Senior Non-Commissioned Officers",
      "fr": "Adjudants, officiers mariniers et sous-officiers supérieurs"
    }
  },
  {
    "level": 4,
    "element": ["CA", "RCAF"],
    "title": {
      "en": "Master Corporal",
      "fr": "Caporal-chef"
    },
    "abbreviation": {
      "en": "MCpl",
      "fr": "cplc"
    },
    "category": {
      "en": "Junior Non-Commissioned Members",
      "fr": "Militaires du rang subalternes"
    }
  },
  {
    "level": 4,
    "element": ["RCN"],
    "title": {
